App_login/urls.py
from django.urls import path
from App_login import views

app_name = "App_login"

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
]

App_posts/urls.py
from django.urls import path
from App_posts import views

app_name = 'App_posts'

urlpatterns = [
    path("", views.home, name='home'),
]

authSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_login.urls')),
    path('posts/', include('App_posts.urls')),
    path("", views.home, name='home'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    

App_posts/models.py
from django.db import models

# Create your models here.

App_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import fields
from App_login import models
from App_login.models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="",
    widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="",
    widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True, label="",
    widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(required=True, label="",
    widget=forms.PasswordInput(attrs={'placeholder':'Password confirmation'}))
    
    class Meta:
        model = User
        fields = ('email','username','password1','password2')
    
    

class LoginUser(AuthenticationForm):
    username = forms.CharField(required=True, label="",
    widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(required=True, label="",
    widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    class Meta:
        model = User
        fields = ('username','password')
    
class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile
        exclude = ('user',)
    

App_login/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, HttpResponsePermanentRedirect
from App_login.forms import CreateNewUser, LoginUser, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from App_login.models import UserProfile
from django.contrib.auth.decorators import login_required

# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method=='POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponsePermanentRedirect(reverse('App_login:login'))
    return render(request, 'App_login/signup.html', context={'title':'sign up . Instagram', 'form':form})

def login_page(request):
    form = LoginUser()
    if request.method=='POST':
        form = LoginUser(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username , password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_posts:home'))
    return render(request, 'App_login/login.html', context={'title':'Login . Social', 'form':form})

@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method=='POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
    return render(request, 'App_login/profile.html', context={'form': form, 'title': 'Edit profile . Social'})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_login:login'))

App_posts/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request, 'App_posts/home.html', context={'title':'Posts'})

templates/App_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
{{title}}
{% endblock title_block %}

{% block css_block %}
    <style>
        .signupform{
            width : 550px;
            border : 1px solid #ccc;
            padding : 10px;
        }
        .login{
            width : 550px;
            padding : 30px;
            border : 1px solid #ccc;
        }
    </style>
{% endblock css_block %}

{% block body_block %}

<center>

<div class="login">
    <h3>Login from here</h3>

    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" style="width:100%">Login</button>
    </form>
</div>  
<br>  
<div class="signupform">
    <p>Don't Have an account? <a href="{% url 'App_login:sign_up' %}">Sign Up</a></p>
</div>
</center>



{% endblock body_block %}

templates/App_login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
{{title}}
{% endblock title_block %}


{% block body_block %}

<form method="POST" entype=>

    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" style="width:100%">Login</button>

</form>

{% endblock body_block %}

templates/App_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
{{title}}
{% endblock title_block %}

{% block css_block %}
    <style>
        .signupform{
            width : 550px;
            border : 1px solid #ccc;
            padding : 30px;
        }
        .login{
            width : 550px;
            padding : 10px;
            border : 1px solid #ccc;
        }
    </style>
{% endblock css_block %}

{% block body_block %}

<center>

<div class="signupform">
    <h3>Sign Up from here</h3>

    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" style="width:100%">Sign Up</button>
    </form>
</div>  
<br>  
<div class="login">
    <p>Have an account? <a href="{% url 'App_login:login' %}">Login</a></p>
</div>
</center>



{% endblock body_block %}

templates/App_posts/home.html
{% extends 'navbar.html' %}
{% block title_block %}
{{title}}
{% endblock title_block %}


{% block body_block %}

<div class="jumbotron">
    <h1 class="display-4">Hello, {{user.username}}</h1>
    <p class="lead">This is a authentication site.</p>
    <hr class="my-4">
    <p>Thank you for logging in and testing this site. Visit again.</p>
    <a class="btn btn-primary btn-lg" href="{% url 'App_login:logout' %}" role="button">Log out</a>
</div>

{% endblock body_block %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>
        {% block title_block %}
        
        {% endblock title_block %}
    </title>
    {% block css_block %}

    {% endblock css_block %}
</head>
<body>
    <div class="container" style="padding-top:20px">

        {% block body_block %}
        
        {% endblock body_block %}

    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>
        {% block title_block %}
        
        {% endblock title_block %}
    </title>
    {% block css_block %}

    {% endblock css_block %}
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'App_posts:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_login:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
                {% if user.user_profile.profile_pic %}
                <a class="nav-link" ><img src="/media/{{user.user_profile.profile_pic}}" width="40px" height="40px" class="rounded-circle"></a>
                {% else %}
                <a class="nav-link" ><img src="/media/default.png" width="40px" height="40px" class="rounded-circle"></a>
                {% endif %}
            </li>
           
          </ul>
        </div>
      </nav>

    <div class="container" style="padding-top:20px">

        {% block body_block %}
        
        {% endblock body_block %}

    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>